Add Ruff, Djlint and v5 branch changes
Kozea/MakeCitron pull request #8
Opened 2024-07-01 14:42 UTC by alexandreNoens

## This Pull Request is not intended to be merged

When moving from `v2` to `v3`, the use of **Docker** was added. 
However, for certain projects, we do not need Docker. Therefore, we created a `v3-legacy` branch that does not use Docker but includes the updates made to the branch which continued with the use of Docker (MakeCitron/v5).

2024-07-02 19:26 UTC, glepretre commented on MakeCitron.Makefile
> +BASEVERSION ?= v3
Will conflict with already existing v3 branch? I expected something like `v3-legacy`

2024-07-02 19:26 UTC, glepretre commented on base.Makefile
> +SHELL := bash
Why do we need to simplify? Does not seem very UNIX to me.

2024-07-02 19:26 UTC, glepretre commented on dots/pyproject.toml
> +combine-as-imports = true
Would be nice to fix the new line at the end of file.

2024-07-05 09:10 UTC, glepretre reviewed
Mob: To review please @gentooboontoo

2024-07-05 09:10 UTC, glepretre commented on MakeCitron.Makefile
> +BASEVERSION ?= v3
Mob review: it's just an example.

2024-07-05 09:10 UTC, glepretre commented on base.Makefile
> +SHELL := bash
mob: Changed between v2 and v3, not related to this branch.

2024-07-12 12:33 UTC, glepretre commented
Mob : ping @gentooboontoo

2024-07-15 08:32 UTC, gentooboontoo requested changes

2024-07-15 08:32 UTC, gentooboontoo commented on base.Makefile
> +	$(RUFF) check $(LINTED_PYTHON_DIRS)
djLint-related lines are missing from backport (`TEMPLATE_DIRS` variable too).

2024-07-15 10:21 UTC, gentooboontoo approved these changes

2024-07-15 10:22 UTC, gentooboontoo commented
Rappel probablement inutile mais à clôturer sans merger une fois les revues terminées.

2024-07-15 10:23 UTC, closed without merging